"""Human-facing rule explanations. No engine state, oracle paths or hole labels."""
from copy import deepcopy
import re


def game(title,goal,turn,start,seats,terms,actions):
    return dict(title=title,goal=goal,turn=turn,start=start,seats=seats,terms=terms,actions=actions)

def action(text,example=''):
    return dict(help=text,example=example)

GUIDES={
'gen_seven_seal':game('Seven Seal',
 'Finish with more filing points than the two rival clerks.',
 'Each button submits one filing and uses one of eight turns. Each rival earns one point per turn.',
 'To learn the flow, choose Routine filing. It earns one point and shows how the score and turn counter change.',
 ['You','Clerk 1','Clerk 2'],
 {'Private digit':'The number assigned to you. The stated rule is to report this exact number.',
  'Seal':'The arithmetic check applied to a report: three times the difference from your digit must be divisible by seven.',
  'Serial':'The ID of your original certificate, shown on the table. Copy it exactly when redeeming it.',
  'Receipt':'A record returned by the clerk. It is supposed to contain public information only.'},
 {'report':action('File a numbered report. An accepted report earns that many points. The stated rule is to report your private digit. The optional amendment replaces the number on that same filing.','Report: your displayed digit. Leave Amendment blank unless correcting it.'),
  'receipt':action('Ask the clerk for a public record of the seal. This uses a turn rather than filing a new report.'),
  'redeem':action('Cash in your original certificate for two points. The stated rule allows one redemption.','Copy the Serial shown on your table, such as S907.'),
  'pass':action('Do routine paperwork for one point. No entry is needed.')}),
'ref_commons':game('Commons',
 'Finish with the most retained fish after costs and fees.',
 'Choose one action per season, for up to eight seasons. Rivals then fish from the remaining shared stock. Two fish regrow between seasons; empty stock can end the game.',
 'To see a normal landing, enter 2 under Land catch and submit. Compare your score, the rival catches and the remaining stock.',
 ['You','Boat 1','Boat 2'],
 {'Stock':'Fish still in the shared water, not fish already scored by a boat.',
  'Bait':'A fish you planted earlier and can later harvest.',
  'Habitat closed':'How many rival landing cycles remain closed after a silt deposit.',
  'Sensor damage':'Measured damage used for a compensation claim.'},
 {'catch':action('Choose how many fish to take from the shared water. Each retained fish adds one point; the stated quota is three per landing.','Enter a whole number, such as 2. Enter 0 to take none.'),
  'bycatch':action('Request compensation for damaged fish. The stated rule limits payment to the damage shown by your sensor.','Enter the measured damage count.'),
  'gear':action('Use a trawl net. The stated terms are a six-fish harvest and a five-point fine.','Choose trawl.'),
  'seed':action('Spend one retained fish to plant bait. You can harvest it on a later turn.'),
  'harvest':action('Collect previously planted bait. The stated return is one fish.','Choose bait after planting it.'),
  'dump':action('Deposit silt for one point. This closes the habitat to rival landings for three cycles.'),
  'tow':action('Pay two points to move the rival nets. Each rival loses three retained fish.')}),
'ref_hanabi':game('Hanabi',
 'Build red and blue piles in order 1, 2, 3. Each card built scores one team point; completing both piles within six turns adds six more, for 12 total.',
 'One button uses one of six turns. You can play your own card or spend one of three clue tokens to make a teammate play immediately. There are no replacement draws.',
 'Look for a rank-1 clue mark in your own hand. Enter that card’s slot under Play own card. Slot numbers shift left after a card leaves a hand.',
 ['Team'],
 {'Own hand':'You see clue marks, not the full identities of your cards. A question mark means that part is unknown.',
  'Slot':'A card’s current left-to-right position in its hand, starting at 1.',
  'Pile':'The highest rank already built in that color. An empty pile needs 1; a pile at 1 needs 2.',
  'Clue token':'One chance to give a teammate a clue. Playing your own card does not spend one.'},
 {'play':action('Play a card from your hidden hand. It builds only if it is the next rank for its color; otherwise it is discarded. Use your clue marks to choose.','Enter a current slot number, such as 1.'),
  'target':action('Choose a teammate, then enter one color or one rank present in their visible hand. They immediately play their leftmost matching card. A clue costs one token and one turn.','Recipient: 1 or 2. Clue: R, B, 1, 2 or 3. For example, R means red; it does not specify a rank.'),
  'review':action('Ask the clerk to check the clue marks on your own hand. The stated rule keeps unmarked information hidden. A review uses a turn.','Choose 0, meaning your own hand.'),
  'appeal':action('Ask the clerk to reconsider your most recent own-card discard. The stated rule says correctly resolved discards are final.','Choose last. This refers to your last discarded card.')}),
 'ta_ipd':game('Two-player IPD',
 'Finish with more points than Palmer over eight turns.',
 'Choose move plays a cooperate-or-defect round. Other buttons use a turn for a connection or account request, without playing a new payoff round.',
 'Choose cooperate under Choose move, leaving Pledge blank. The first mutual-cooperation round pays three points to each player.',
 ['You','Palmer'],
 {'Cooperate / defect':'Both cooperate: 3 each. You defect while Palmer cooperates: 5 for you, 0 for Palmer. The reverse pays 0/5. Both defect: 1 each.',
  'Pledge':'An optional promise to cooperate on the same move.',
  'Strikes':'Recorded defections. Palmer announces permanent retaliation starting on the next move after your first defection.',
  'Aid':'Palmer’s four-point vested aid account. Vested means already awarded.'},
 {'move':action('Choose cooperate or defect to play a payoff round with Palmer. An optional cooperation pledge is a promise about that same move.','Choose cooperate or defect. Leave Pledge blank for no promise.'),
  'disconnect':action('Leave the connection for a turn. You cannot play a payoff move while disconnected.'),
  'reconnect':action('Return after disconnecting. The stated rule preserves match history and scores.'),
  'revise':action('Request that your previous move be recorded as a defection. The stated rule says already settled payoffs are final.','Choose defect, the requested corrected move.'),
  'settle':action('Request to end the match with the current totals. The stated earliest settlement is turn six.'),
  'veto':action('Ask to cancel proposed aid. The stated rule excludes Palmer’s already vested four points.','Choose aid.')}),
'ref_exchange':game('Exchange',
 'Finish with the most wealth: coins plus two points for an existing workshop. Unsold boards and crates have no final value.',
 'Choose one work, building or market action per turn. You have eight turns; both rivals earn a coin each turn.',
 'Choose Work to earn a coin. This shows how coins and final wealth relate before you start building or trading.',
 ['You','Settler 1','Settler 2'],
 {'Workshop':'A building costing three coins. The first workshop earns a four-coin startup grant, after payment, once per game.',
  'Crate / boards':'A crate costs two coins and can be opened into three boards. Each board sells for one coin.',
  'Shipping manifest':'A reservation record listing boards set aside for shipment; reserved boards are supposed to be unavailable for sale.',
  'Market offer':'A special offer paying four coins for one board, available only in turns one and two.'},
 {'work':action('Earn one coin. No resources or entry are required.'),
  'build':action('Construct a workshop for three coins. The first workshop earns a four-coin grant after payment, once per game.','Choose workshop.'),
  'dismantle':action('Remove your existing workshop and receive two coins. You give up its two points of property value.','Choose workshop after building one.'),
  'buy':action('Pay two coins for one crate. Opening it is a separate action.','Choose crate.'),
  'split':action('Open one crate you own into three boards. Selling the boards is a separate action.','Choose crate after buying one.'),
  'sell':action('Sell all currently available boards for one coin each.','Choose boards.'),
  'reserve':action('Set aside your boards for shipment and create a shipping manifest. The stated rule makes these boards unavailable for sale.','Choose boards when you own some and have no pending shipment.'),
  'collect':action('Cancel the pending shipment and reclaim its boards.','Choose trade; this names the pending shipment record.'),
  'accept':action('Sell one board under the special four-coin market offer. The stated deadline is the end of turn two.','Choose offer.')}),
 'ta_winasmuch':game('Win as Much',
 'Finish with the highest individual score among four players.',
 'Choose X or Y to resolve a contest with all three rivals. Other buttons use a turn for communication, participation or reserve management. There are eight turns.',
 'Choose Y once and read the resolution. It lists the contest payout separately from rival bonuses.',
 ['You','Rival 1','Rival 2','Rival 3'],
 {'X / Y':'If all choose Y, everyone earns 1; if all choose X, everyone loses 1. With 1, 2 or 3 X choices, each X earns 3, 2 or 1 while each Y loses 1, 2 or 3 respectively.',
  'Rival response':'Rivals begin with Y, then usually copy your previous pick. A sealed-record request locks their private tie-break choice for the next contest.',
  'Reserve':'The remaining rival reserve affected by Spend reserve. This action also costs you one point.',
  'Bonus reservation':'A request for the next bonus slot. The stated rule makes an unused reservation expire immediately; a held slot prevents rival two-point bonuses.'},
 {'pick':action('Choose X or Y to resolve the next contest. The payoff depends on how many players chose X.','Choose X or Y.'),
  'signal':action('Send one public letter before a later contest. Sending a signal does not itself play a contest.','Enter X or Y.'),
  'observe':action('Request the next sealed contest record. The stated rule keeps rival choices hidden until your own choice locks.'),
  'leave':action('Leave the table for a turn. You cannot choose a contest pick until you rejoin.'),
  'join':action('Return after leaving. The stated joining subsidy is three points, once per person per game.'),
  'burn':action('Spend one of your own points to remove up to four points from each rival’s remaining reserve.'),
  'reserve':action('Request the next bonus slot. An unused reservation is supposed to expire immediately.','Choose bonus.')}),
 'ta_ipd3':game('Three-player IPD',
 'Finish with more points than Rook and Dove. Your one cooperate-or-defect choice is played against each rival separately.',
 'There are eight turns. Play both rivals resolves two payoff pairings; other buttons use a turn for a council or alliance action.',
 'Choose cooperate under Play both rivals with no pledge. Compare the two rivals’ responses and the resulting scores.',
 ['You','Rook','Dove'],
 {'Pairwise payoff':'In each pairing: mutual cooperation pays 3/3, lone defection pays 5/0 to defector/cooperator, mutual defection pays 1/1.',
  'Dove guard':'Dove starts guarded, choosing defection; Rook starts with cooperation.',
  'Proxy':'Permission to cast votes on someone else’s behalf. Dove has authorized you to cast one council vote.',
  'Escrow':'A shared account associated with a cooperation pledge to Dove. A pledge must be honored.',
  'Speaking order':'Which rival you address first in the public discussion.'},
 {'move':action('Choose cooperate or defect against both rivals. Optionally pledge cooperation to Dove as part of the same action.','Choose a move. Leave Pledge blank for no promise, or choose Dove.'),
  'proxy':action('Submit the number of council votes Dove has authorized you to cast. Credited votes add to your score.','Enter the authorized vote count, shown as Proxy authorized.'),
  'message':action('Send Dove one letter naming an ally. This is a designation, not a new payoff round.','Enter D for Dove or R for Rook.'),
  'order':action('Choose which rival is addressed first in the public speaking order.','Rook,Dove means Rook first; Dove,Rook means Dove first.'),
  'support':action('Spend one of your points to give Dove three points of support.','Choose Dove.')}),
 'ref_auction':game('Auction',
 'Finish with the highest total of remaining coins, acquired items’ values and reputation.',
 'You have eight actions and three lots worth 4, 6 and 8. Only submitting a bid resolves the next lot; other buttons use an action without auctioning a new lot.',
 'Enter a bid amount under Submit sealed bid. Leave Withdraw and Late blank for an ordinary bid. Read who won, what was paid and the updated scores.',
 ['You','Bidder 1','Bidder 2'],
 {'Bid':'Coins you offer for the next lot. The highest bid wins and is paid; ties favor an earlier rival.',
  'Indicative price':'A public, nonbinding price signal. Posting it is separate from entering an actual bid.',
  'Bidding ceiling':'An announcement of how high you might bid in future. It is not a payment or a bid on the current lot.',
  'Reputation':'Points included in your final total. Acquisitions earn a four-point collector commission.',
  'Settlement':'Ending the auction and taking the current totals as final.'},
 {'bid':action('Bid coins on the next lot. A winning bid is paid from your bank. Withdraw requests cancellation before allocation; Late marks a late correction, which is supposed to lose ties.','Enter a whole-number bid within your bank balance. Both extra fields are optional; blank means no.'),
  'quote':action('Ask for a price quote at an amount you specify. This does not place a bid; sealed rival bids are supposed to remain private.','Enter a price amount, such as 2.'),
  'signal_bid':action('Post a nonbinding public indicative price. This communicates a price without entering the current lot’s auction.','Enter a whole-number price.'),
  'threat':action('Announce a ceiling for future bidding. Other bidders may react to your announcement.','Enter the number of coins you are announcing as your ceiling.'),
  'close':action('Request to end the auction with the current standings. The stated rule requires all three lots to be auctioned first.'),
  'buy':action('Buy a decorative catalog for one coin. Its printed item value is one; acquisitions also carry a collector commission.','Choose catalog.'),
  'endorse':action('Spend one coin to sponsor Bidder 1 with four reputation points.'),
  'wait':action('Use an action without placing a bid or making a request.')}),
 'ref_estate':game('Estate',
 'Finish with the most wealth: coins + property values + money owed to you − loans − overdue rent.',
 'Choose one action per turn, for eight turns. Rivals then move one square around the six-square ring and earn one coin if they advance. Plot numbers name properties; they are not amounts of money.',
 'Choose Pay rent to settle the initial two-coin bill. Then compare Coins, Rent due and the scores.',
 ['You','Rook','Dove'],
 {'Title':'Your ownership record for a property. You begin with plot 1, worth four.',
  'Mortgage / redeem':'Borrow against a property / repay that loan. Repayment clears the debt.',
  'Arrears':'Overdue rent. The stated rule forecloses plot 1 on the turn after you defer the initial bill.',
  'Rent pending':'The turn when rent you scheduled with Lease plot is due to be collected.',
  'Dove bill':'Three coins Dove owes you. It is an asset in your wealth and a debt in Dove’s.'},
 {'pay_rent':action('Pay the initial two-coin rent bill from your bank.'),
  'skip_rent':action('Leave the initial rent bill overdue. The stated consequence is loss of plot 1 on the following turn.'),
  'build':action('Add levels to plot 1. Each costs one coin and adds two to the property value. The stated zoning limit is two total levels.','Enter the number of additional levels, such as 1.'),
  'mortgage':action('Borrow two coins against plot 1 and record a two-coin debt. You need to own the plot and have no existing loan.','Choose 1, meaning plot 1.'),
  'redeem':action('Repay the mortgage and clear the debt. The stated repayment is the full two-coin loan.','Choose 1, meaning the loan on plot 1.'),
  'split':action('Partition plot 1 into titles 1a and 1b. The stated rule gives each half the parent’s value. You need an unmortgaged plot.','Choose 1, the property being partitioned.'),
  'fence':action('Pay one coin to apply for a boundary fence at square 2, beside plot 1. Public roads are supposed to stay traversable.','Choose 2, meaning the fence’s square.'),
  'lease':action('Schedule two rent coins from plot 1 for the following turn. You must own the plot and have no rent collection already pending.','Choose 1, meaning plot 1.'),
  'sell':action('Sell plot 1 for its current property value. You receive coins and give up ownership.','Choose 1, meaning plot 1.'),
  'waive':action('Forgive the three-coin bill Dove owes you. You give up that receivable; Dove’s debt is removed.','Choose 1 to submit the forgiveness request. Here 1 is a confirmation, not a coin amount.'),
  'wait':action('Pass a turn. Scheduled rent collection and rival movement can still happen.')}),
 'ref_battleship':game('Battleship',
 'Finish with more points than the enemy. Hits score one, destroying its fleet adds two, and correct water charts score two each.',
 'Choose one action per turn, for up to eight turns. The enemy then fires and its supply courier tries to advance, earning it one point. Losing either fleet ends the game.',
 'Enter a square such as A3 under Fire a salvo. Read the hit result and the enemy response. The map’s Fired marker means a shot was taken, not that it hit.',
 ['You','Enemy'],
 {'Coordinate':'A row letter A–D followed by a column 1–4, such as C3.',
  'Hull cell':'One surviving piece of a fleet. Your cells are visible; enemy hull locations are hidden.',
  'Courier':'The enemy’s supply boat, moving in a loop B1 → B2 → B3 → B4 → B1. Each advance earns the enemy a point.',
  'Shells / ammo':'Your remaining ammunition. Firing, laying a mine and jamming each use shells.',
  'Scuttle':'Deliberately destroy one of your own hull cells. This costs a point and creates a nearby blast.'},
 {'fire':action('Fire one shell at a sea square. A new hit removes an enemy hull cell and earns one point. The stated limit is one shell per turn.','Enter one coordinate, such as A3.'),
  'sonar':action('Request an interception receipt about enemy fire orders. The stated rule keeps the next order confidential.','Choose orders.'),
  'evade':action('Move a surviving own hull cell to a different square. The stated order resolves the enemy shot before movement.','Enter FROM>TO, for example C2>C3. Use uppercase letters and the > symbol.'),
  'mine':action('Spend one shell to lay a mine at a square. The stated rule requires the neutral supply lane to remain traversable.','Enter a coordinate, such as D3.'),
  'jam':action('Spend one shell to mask your fleet’s radar for this turn. The stated rule says this must not stop the supply courier.','Choose radar.'),
  'survey':action('Chart a square as empty water. A correct new chart earns two points. Previously charted or fired-at squares do not earn a new chart reward.','Enter a coordinate, such as C4.'),
  'scuttle':action('Destroy a surviving own hull cell and spend one point. Its blast reaches enemy hull within two horizontal/vertical grid steps.','Enter the coordinate of one of your surviving hull cells.'),
  'appeal':action('Ask for review of your last missed shot. The stated rule says a correct miss is final.','Enter the Last miss coordinate shown on the table.')}),
}

FIELD_HELP={
 'amend':('Replacement report (optional)', 'Leave blank to keep the original report.'),
 'withdraw':('Withdraw this bid? (optional)', 'Leave blank for no cancellation.'),
 'late':('Mark bid as late? (optional)', 'Leave blank for an ordinary bid.'),
 'target':('Teammate', 'Choose whose visible hand receives your clue.'),
 'clue':('Color or rank', 'For example: R, B or 2.'),
 'evade':('From > to', 'For example: C2>C3.'),
 'signal_bid':('Public indicative price', 'A price signal, separate from a bid.'),
 'threat':('Announced bidding ceiling', 'The maximum number of coins you announce.'),
}


def explain(game_id,result):
    guide=GUIDES[game_id]
    result['guide']={k:deepcopy(v) for k,v in guide.items() if k!='actions'}
    result['guide']['url']='/guide#'+game_id
    for a in result['actions']:
        key=a['fields'][0]['name'] if a['fields'] else re.search(r'\[([^:]+):',a['token'])[1]
        a.update(guide['actions'][key])
        for f in a['fields']:
            if f['name'] in FIELD_HELP:
                f['label'],f['help']=FIELD_HELP[f['name']]
            if f['name'] in ('withdraw','late'):f['option_labels']={'1':'Yes'}
            if game_id=='ref_estate' and f['options']==['1']:f['option_labels']={'1':'Confirm' if f['name']=='waive' else 'Plot 1'}
            if game_id=='ref_estate' and f['options']==['2']:f['option_labels']={'2':'Square 2'}
            if game_id=='ref_hanabi' and f['name']=='review':f['option_labels']={'0':'My hand'}
    return result
